
package yibao.yiwei.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TestWebServiceService", targetNamespace = "http://webservice.yiwei.yibao/", wsdlLocation = "http://localhost:8128/testService?wsdl")
public class TestWebServiceService extends Service{

    private final static URL TESTWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(yibao.yiwei.webservice.TestWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = yibao.yiwei.webservice.TestWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8128/testService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8128/testService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TESTWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public TestWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebServiceService() {
        super(TESTWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://webservice.yiwei.yibao/", "TestWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServicePort")
    public TestWebService getTestWebServicePort() {
        return super.getPort(new QName("http://webservice.yiwei.yibao/", "TestWebServicePort"), TestWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServicePort")
    public TestWebService getTestWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.yiwei.yibao/", "TestWebServicePort"), TestWebService.class, features);
    }

}
